#!/bin/sh
#
# Runs the Revapi analysis of com.unblu.openapi:models-v4 8.17.1 -> 8.18.0 and
# writes, next to this script:
#
#   report.txt   the report of org.revapi:revapi-reporter-text
#   report.json  the report of org.revapi:revapi-reporter-json
#
# Generated by revapi/create-report-folder.sh -- do not edit by hand. Re-create it with:
#
#   ../../create-report-folder.sh 8.17.1 8.18.0 models-v4
#
# The analysed archives are read from the local Maven repository; set the MAVEN_REPO
# environment variable to use another location. `create-report-folder.sh` downloads
# them if they are missing.
#
# What is reported and what is ignored is configured in revapi/revapi-config.json.

set -eu

DIR=$(cd "$(dirname "$0")" && pwd)
REVAPI_DIR=$(cd "$DIR/../.." && pwd)
MAVEN_REPO=${MAVEN_REPO:-$HOME/.m2/repository}

OLD_API="$MAVEN_REPO/com/unblu/openapi/models-v4/8.17.1/models-v4-8.17.1.jar"

OLD_SUPPLEMENTARY="$MAVEN_REPO/io/swagger/swagger-annotations/1.5.15/swagger-annotations-1.5.15.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-annotations/2.14.1/jackson-annotations-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-core/2.14.1/jackson-core-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-databind/2.14.1/jackson-databind-2.14.1.jar"

NEW_API="$MAVEN_REPO/com/unblu/openapi/models-v4/8.18.0/models-v4-8.18.0.jar"

NEW_SUPPLEMENTARY="$MAVEN_REPO/io/swagger/swagger-annotations/1.5.15/swagger-annotations-1.5.15.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-annotations/2.14.1/jackson-annotations-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-core/2.14.1/jackson-core-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-databind/2.14.1/jackson-databind-2.14.1.jar"

"$REVAPI_DIR"/revapi.java \
    --extensions=org.revapi:revapi-java:0.28.4,org.revapi:revapi-reporter-text:0.15.1,org.revapi:revapi-reporter-json:0.5.1 \
    --old "$OLD_API" \
    --old-supplementary "$OLD_SUPPLEMENTARY" \
    --new "$NEW_API" \
    --new-supplementary "$NEW_SUPPLEMENTARY" \
    --config-files "$REVAPI_DIR/revapi-config.json" \
    -Drevapi.reporter.text.minSeverity=POTENTIALLY_BREAKING \
    -Drevapi.reporter.json.minSeverity=POTENTIALLY_BREAKING \
    -Drevapi.reporter.json.output="$DIR/report.json" \
    -Drevapi.reporter.json.indent=true \
    > "$DIR/report.txt"
