#!/bin/sh
#
# Creates the report folder for two consecutive releases of the Unblu java client
# (https://github.com/unblu/openapi) and writes the `run-revapi.sh` script that
# produces the reports in it.
#
# Usage:
#
#   ./create-report-folder.sh <old version> <new version> [<artifact id>...]
#
# Example:
#
#   ./create-report-folder.sh 8.39.3 8.40.4
#
# This creates, relative to this script:
#
#   <old version>_<new version>/<artifact id>/run-revapi.sh
#
# When no artifact id is given, all artifacts listed in ARTIFACTS are handled.
#
# This script only *creates* the `run-revapi.sh` scripts, it does not run them. Use
# `./run-revapi.sh <old version> <new version>` for that.
#
# The point of this script is to resolve the classpath of each artifact with Maven, so
# that the generated `run-revapi.sh` is a plain, self-contained record of the command
# that produces the two report files. Revapi's own GAV resolution
# (`--old-gavs`/`--new-gavs`) cannot be used instead: it only considers the `compile`
# and `provided` scopes, whereas `models-v4` declares its Jackson dependencies with the
# `runtime` scope, which would leave those classes off the analysis classpath and
# report them as `java.missing.oldClass`/`newClass`. Revapi also ignores
# `--old-supplementary`/`--new-supplementary` when the GAV options are used.

set -eu

BASE_DIR=$(cd "$(dirname "$0")" && pwd)

GROUP_ID=com.unblu.openapi
ARTIFACTS="jersey3-client-v4 models-v4"

REVAPI_JAVA_VERSION=0.28.4
REVAPI_REPORTER_TEXT_VERSION=0.15.1
REVAPI_REPORTER_JSON_VERSION=0.5.1

if [ $# -lt 2 ]; then
    echo "Usage: $0 <old version> <new version> [<artifact id>...]" >&2
    exit 1
fi

OLD_VERSION=$1
NEW_VERSION=$2
shift 2

if [ $# -gt 0 ]; then
    ARTIFACTS=$*
fi

# Note: `revapi-basic-features` (which provides the `revapi.differences` extension used
# by `revapi-config.json`) is part of the Revapi CLI itself. Listing it here as well
# would load it twice and make the analysis fail with a "Duplicate key regex" error.
EXTENSIONS="org.revapi:revapi-java:$REVAPI_JAVA_VERSION"
EXTENSIONS="$EXTENSIONS,org.revapi:revapi-reporter-text:$REVAPI_REPORTER_TEXT_VERSION"
EXTENSIONS="$EXTENSIONS,org.revapi:revapi-reporter-json:$REVAPI_REPORTER_JSON_VERSION"

WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

LOCAL_REPO=$(mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)

# Prints the runtime classpath of the given artifact, one entry per line, starting with
# the artifact's own jar. Artifacts missing from the local repository are downloaded.
resolve_classpath() {
    artifact=$1
    version=$2

    cat > "$WORK_DIR/pom.xml" <<EOF
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.unblu.openapi.revapi</groupId>
  <artifactId>classpath-resolver</artifactId>
  <version>1</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>$GROUP_ID</groupId>
      <artifactId>$artifact</artifactId>
      <version>$version</version>
    </dependency>
  </dependencies>
</project>
EOF

    mvn -q -f "$WORK_DIR/pom.xml" dependency:build-classpath \
        -Dmdep.outputFile="$WORK_DIR/classpath.txt" \
        -Dmdep.includeScope=runtime \
        -Dmdep.pathSeparator=: \
        > /dev/null

    tr ':' '\n' < "$WORK_DIR/classpath.txt" | sed "s|^$LOCAL_REPO/|\$MAVEN_REPO/|"
}

# Reads a list of paths on stdin, one per line, and prints them as a single
# comma-separated shell string using one line per entry.
format_archive_list() {
    awk 'NR > 1 { printf ",\\\n" } { printf "%s", $0 } END { print "" }'
}

for artifact in $ARTIFACTS; do
    output_dir="$BASE_DIR/${OLD_VERSION}_${NEW_VERSION}/$artifact"
    mkdir -p "$output_dir"

    echo "Creating $output_dir/run-revapi.sh"

    old_jar="$artifact-$OLD_VERSION.jar"
    new_jar="$artifact-$NEW_VERSION.jar"

    old_classpath=$(resolve_classpath "$artifact" "$OLD_VERSION")
    new_classpath=$(resolve_classpath "$artifact" "$NEW_VERSION")

    old_api=$(echo "$old_classpath" | grep "/$old_jar\$")
    old_supplementary=$(echo "$old_classpath" | grep -v "/$old_jar\$" | format_archive_list)
    new_api=$(echo "$new_classpath" | grep "/$new_jar\$")
    new_supplementary=$(echo "$new_classpath" | grep -v "/$new_jar\$" | format_archive_list)

    cat > "$output_dir/run-revapi.sh" <<EOF
#!/bin/sh
#
# Runs the Revapi analysis of $GROUP_ID:$artifact $OLD_VERSION -> $NEW_VERSION and
# writes, next to this script:
#
#   report.txt   the report of org.revapi:revapi-reporter-text
#   report.json  the report of org.revapi:revapi-reporter-json
#
# Generated by revapi/create-report-folder.sh -- do not edit by hand. Re-create it with:
#
#   ../../create-report-folder.sh $OLD_VERSION $NEW_VERSION $artifact
#
# The analysed archives are read from the local Maven repository; set the MAVEN_REPO
# environment variable to use another location. \`create-report-folder.sh\` downloads
# them if they are missing.
#
# What is reported and what is ignored is configured in revapi/revapi-config.json.

set -eu

DIR=\$(cd "\$(dirname "\$0")" && pwd)
REVAPI_DIR=\$(cd "\$DIR/../.." && pwd)
MAVEN_REPO=\${MAVEN_REPO:-\$HOME/.m2/repository}

OLD_API="$old_api"

OLD_SUPPLEMENTARY="$old_supplementary"

NEW_API="$new_api"

NEW_SUPPLEMENTARY="$new_supplementary"

"\$REVAPI_DIR"/revapi.java \\
    --extensions=$EXTENSIONS \\
    --old "\$OLD_API" \\
    --old-supplementary "\$OLD_SUPPLEMENTARY" \\
    --new "\$NEW_API" \\
    --new-supplementary "\$NEW_SUPPLEMENTARY" \\
    --config-files "\$REVAPI_DIR/revapi-config.json" \\
    -Drevapi.reporter.text.minSeverity=POTENTIALLY_BREAKING \\
    -Drevapi.reporter.json.minSeverity=POTENTIALLY_BREAKING \\
    -Drevapi.reporter.json.output="\$DIR/report.json" \\
    -Drevapi.reporter.json.indent=true \\
    > "\$DIR/report.txt"
EOF

    chmod +x "$output_dir/run-revapi.sh"
done
