#!/bin/sh
#
# Runs the Revapi analysis of com.unblu.openapi:jersey3-client-v4 8.6.0 -> 8.6.1 and
# writes, next to this script:
#
#   report.txt   the report of org.revapi:revapi-reporter-text
#   report.json  the report of org.revapi:revapi-reporter-json
#
# Generated by revapi/create-report-folder.sh -- do not edit by hand. Re-create it with:
#
#   ../../create-report-folder.sh 8.6.0 8.6.1 jersey3-client-v4
#
# The analysed archives are read from the local Maven repository; set the MAVEN_REPO
# environment variable to use another location. `create-report-folder.sh` downloads
# them if they are missing.
#
# What is reported and what is ignored is configured in revapi/revapi-config.json.

set -eu

DIR=$(cd "$(dirname "$0")" && pwd)
REVAPI_DIR=$(cd "$DIR/../.." && pwd)
MAVEN_REPO=${MAVEN_REPO:-$HOME/.m2/repository}

OLD_API="$MAVEN_REPO/com/unblu/openapi/jersey3-client-v4/8.6.0/jersey3-client-v4-8.6.0.jar"

OLD_SUPPLEMENTARY="$MAVEN_REPO/com/unblu/openapi/models-v4/8.6.0/models-v4-8.6.0.jar,\
$MAVEN_REPO/org/glassfish/jersey/core/jersey-client/3.1.2/jersey-client-3.1.2.jar,\
$MAVEN_REPO/jakarta/ws/rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs-api-3.1.0.jar,\
$MAVEN_REPO/org/glassfish/jersey/core/jersey-common/3.1.2/jersey-common-3.1.2.jar,\
$MAVEN_REPO/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar,\
$MAVEN_REPO/org/glassfish/hk2/osgi-resource-locator/1.0.3/osgi-resource-locator-1.0.3.jar,\
$MAVEN_REPO/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar,\
$MAVEN_REPO/org/glassfish/jersey/media/jersey-media-multipart/3.1.2/jersey-media-multipart-3.1.2.jar,\
$MAVEN_REPO/org/jvnet/mimepull/mimepull/1.9.15/mimepull-1.9.15.jar,\
$MAVEN_REPO/org/glassfish/jersey/media/jersey-media-json-jackson/3.1.2/jersey-media-json-jackson-3.1.2.jar,\
$MAVEN_REPO/org/glassfish/jersey/ext/jersey-entity-filtering/3.1.2/jersey-entity-filtering-3.1.2.jar,\
$MAVEN_REPO/com/fasterxml/jackson/module/jackson-module-jakarta-xmlbind-annotations/2.14.1/jackson-module-jakarta-xmlbind-annotations-2.14.1.jar,\
$MAVEN_REPO/jakarta/xml/bind/jakarta.xml.bind-api/4.0.0/jakarta.xml.bind-api-4.0.0.jar,\
$MAVEN_REPO/jakarta/activation/jakarta.activation-api/2.1.0/jakarta.activation-api-2.1.0.jar,\
$MAVEN_REPO/org/glassfish/jersey/inject/jersey-hk2/3.1.2/jersey-hk2-3.1.2.jar,\
$MAVEN_REPO/org/glassfish/hk2/hk2-locator/3.0.4/hk2-locator-3.0.4.jar,\
$MAVEN_REPO/org/glassfish/hk2/external/aopalliance-repackaged/3.0.4/aopalliance-repackaged-3.0.4.jar,\
$MAVEN_REPO/org/glassfish/hk2/hk2-api/3.0.4/hk2-api-3.0.4.jar,\
$MAVEN_REPO/org/glassfish/hk2/hk2-utils/3.0.4/hk2-utils-3.0.4.jar,\
$MAVEN_REPO/org/javassist/javassist/3.29.0-GA/javassist-3.29.0-GA.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-core/2.14.1/jackson-core-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-annotations/2.14.1/jackson-annotations-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-databind/2.14.1/jackson-databind-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.14.1/jackson-datatype-jsr310-2.14.1.jar,\
$MAVEN_REPO/io/swagger/swagger-annotations/1.5.15/swagger-annotations-1.5.15.jar"

NEW_API="$MAVEN_REPO/com/unblu/openapi/jersey3-client-v4/8.6.1/jersey3-client-v4-8.6.1.jar"

NEW_SUPPLEMENTARY="$MAVEN_REPO/com/unblu/openapi/models-v4/8.6.1/models-v4-8.6.1.jar,\
$MAVEN_REPO/org/glassfish/jersey/core/jersey-client/3.1.2/jersey-client-3.1.2.jar,\
$MAVEN_REPO/jakarta/ws/rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs-api-3.1.0.jar,\
$MAVEN_REPO/org/glassfish/jersey/core/jersey-common/3.1.2/jersey-common-3.1.2.jar,\
$MAVEN_REPO/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar,\
$MAVEN_REPO/org/glassfish/hk2/osgi-resource-locator/1.0.3/osgi-resource-locator-1.0.3.jar,\
$MAVEN_REPO/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar,\
$MAVEN_REPO/org/glassfish/jersey/media/jersey-media-multipart/3.1.2/jersey-media-multipart-3.1.2.jar,\
$MAVEN_REPO/org/jvnet/mimepull/mimepull/1.9.15/mimepull-1.9.15.jar,\
$MAVEN_REPO/org/glassfish/jersey/media/jersey-media-json-jackson/3.1.2/jersey-media-json-jackson-3.1.2.jar,\
$MAVEN_REPO/org/glassfish/jersey/ext/jersey-entity-filtering/3.1.2/jersey-entity-filtering-3.1.2.jar,\
$MAVEN_REPO/com/fasterxml/jackson/module/jackson-module-jakarta-xmlbind-annotations/2.14.1/jackson-module-jakarta-xmlbind-annotations-2.14.1.jar,\
$MAVEN_REPO/jakarta/xml/bind/jakarta.xml.bind-api/4.0.0/jakarta.xml.bind-api-4.0.0.jar,\
$MAVEN_REPO/jakarta/activation/jakarta.activation-api/2.1.0/jakarta.activation-api-2.1.0.jar,\
$MAVEN_REPO/org/glassfish/jersey/inject/jersey-hk2/3.1.2/jersey-hk2-3.1.2.jar,\
$MAVEN_REPO/org/glassfish/hk2/hk2-locator/3.0.4/hk2-locator-3.0.4.jar,\
$MAVEN_REPO/org/glassfish/hk2/external/aopalliance-repackaged/3.0.4/aopalliance-repackaged-3.0.4.jar,\
$MAVEN_REPO/org/glassfish/hk2/hk2-api/3.0.4/hk2-api-3.0.4.jar,\
$MAVEN_REPO/org/glassfish/hk2/hk2-utils/3.0.4/hk2-utils-3.0.4.jar,\
$MAVEN_REPO/org/javassist/javassist/3.29.0-GA/javassist-3.29.0-GA.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-core/2.14.1/jackson-core-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-annotations/2.14.1/jackson-annotations-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/core/jackson-databind/2.14.1/jackson-databind-2.14.1.jar,\
$MAVEN_REPO/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.14.1/jackson-datatype-jsr310-2.14.1.jar,\
$MAVEN_REPO/io/swagger/swagger-annotations/1.5.15/swagger-annotations-1.5.15.jar"

"$REVAPI_DIR"/revapi.java \
    --extensions=org.revapi:revapi-java:0.28.4,org.revapi:revapi-reporter-text:0.15.1,org.revapi:revapi-reporter-json:0.5.1 \
    --old "$OLD_API" \
    --old-supplementary "$OLD_SUPPLEMENTARY" \
    --new "$NEW_API" \
    --new-supplementary "$NEW_SUPPLEMENTARY" \
    --config-files "$REVAPI_DIR/revapi-config.json" \
    -Drevapi.reporter.text.minSeverity=POTENTIALLY_BREAKING \
    -Drevapi.reporter.json.minSeverity=POTENTIALLY_BREAKING \
    -Drevapi.reporter.json.output="$DIR/report.json" \
    -Drevapi.reporter.json.indent=true \
    > "$DIR/report.txt"
